// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: internal/testpb/test.proto

// Package tests holds fixtures for exercising field behavior and field
// masks. It is not part of the public API.

package testpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shipment exercises field behavior (AIP-203) and field masks (AIP-134).
type Shipment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Origin      string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Notes       string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	CarrierCode string                 `protobuf:"bytes,6,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	Carrier     *Carrier               `protobuf:"bytes,7,opt,name=carrier,proto3" json:"carrier,omitempty"`
	LineItems   []*LineItem            `protobuf:"bytes,8,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	KeyedItems  map[string]*LineItem   `protobuf:"bytes,9,rep,name=keyed_items,json=keyedItems,proto3" json:"keyed_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A presence-less required bool: `false` is indistinguishable from unset.
	Insured bool `protobuf:"varint,10,opt,name=insured,proto3" json:"insured,omitempty"`
	// An explicit-presence required bool: `false` is a real value.
	Fragile       *bool    `protobuf:"varint,11,opt,name=fragile,proto3,oneof" json:"fragile,omitempty"`
	Labels        []string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_internal_testpb_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{0}
}

func (x *Shipment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Shipment) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Shipment) GetCarrierCode() string {
	if x != nil {
		return x.CarrierCode
	}
	return ""
}

func (x *Shipment) GetCarrier() *Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *Shipment) GetLineItems() []*LineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *Shipment) GetKeyedItems() map[string]*LineItem {
	if x != nil {
		return x.KeyedItems
	}
	return nil
}

func (x *Shipment) GetInsured() bool {
	if x != nil {
		return x.Insured
	}
	return false
}

func (x *Shipment) GetFragile() bool {
	if x != nil && x.Fragile != nil {
		return *x.Fragile
	}
	return false
}

func (x *Shipment) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Carrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TrackingId    string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Carrier) Reset() {
	*x = Carrier{}
	mi := &file_internal_testpb_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Carrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carrier) ProtoMessage() {}

func (x *Carrier) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carrier.ProtoReflect.Descriptor instead.
func (*Carrier) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{1}
}

func (x *Carrier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Carrier) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_internal_testpb_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{2}
}

func (x *LineItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *LineItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentRequest) Reset() {
	*x = UpdateShipmentRequest{}
	mi := &file_internal_testpb_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentRequest) ProtoMessage() {}

func (x *UpdateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateShipmentRequest) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *UpdateShipmentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_internal_testpb_test_proto protoreflect.FileDescriptor

const file_internal_testpb_test_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/testpb/test.proto\x12\x05tests\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x04\n" +
	"\bShipment\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1b\n" +
	"\x06origin\x18\x02 \x01(\tB\x03\xe0A\x02R\x06origin\x12%\n" +
	"\vdestination\x18\x03 \x01(\tB\x03\xe0A\x02R\vdestination\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12&\n" +
	"\fcarrier_code\x18\x06 \x01(\tB\x03\xe0A\x05R\vcarrierCode\x12(\n" +
	"\acarrier\x18\a \x01(\v2\x0e.tests.CarrierR\acarrier\x12.\n" +
	"\n" +
	"line_items\x18\b \x03(\v2\x0f.tests.LineItemR\tlineItems\x12@\n" +
	"\vkeyed_items\x18\t \x03(\v2\x1f.tests.Shipment.KeyedItemsEntryR\n" +
	"keyedItems\x12\x1d\n" +
	"\ainsured\x18\n" +
	" \x01(\bB\x03\xe0A\x02R\ainsured\x12\"\n" +
	"\afragile\x18\v \x01(\bB\x03\xe0A\x02H\x00R\afragile\x88\x01\x01\x12\x1b\n" +
	"\x06labels\x18\f \x03(\tB\x03\xe0A\x02R\x06labels\x1aN\n" +
	"\x0fKeyedItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.tests.LineItemR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_fragile\"H\n" +
	"\aCarrier\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12$\n" +
	"\vtracking_id\x18\x02 \x01(\tB\x03\xe0A\x03R\n" +
	"trackingId\"=\n" +
	"\bLineItem\x12\x15\n" +
	"\x03sku\x18\x01 \x01(\tB\x03\xe0A\x02R\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x86\x01\n" +
	"\x15UpdateShipmentRequest\x120\n" +
	"\bshipment\x18\x01 \x01(\v2\x0f.tests.ShipmentB\x03\xe0A\x02R\bshipment\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB2Z0github.com/protoc-contrib/aip-go/internal/testpbb\x06proto3"

var (
	file_internal_testpb_test_proto_rawDescOnce sync.Once
	file_internal_testpb_test_proto_rawDescData []byte
)

func file_internal_testpb_test_proto_rawDescGZIP() []byte {
	file_internal_testpb_test_proto_rawDescOnce.Do(func() {
		file_internal_testpb_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testpb_test_proto_rawDesc), len(file_internal_testpb_test_proto_rawDesc)))
	})
	return file_internal_testpb_test_proto_rawDescData
}

var file_internal_testpb_test_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_testpb_test_proto_goTypes = []any{
	(*Shipment)(nil),              // 0: tests.Shipment
	(*Carrier)(nil),               // 1: tests.Carrier
	(*LineItem)(nil),              // 2: tests.LineItem
	(*UpdateShipmentRequest)(nil), // 3: tests.UpdateShipmentRequest
	nil,                           // 4: tests.Shipment.KeyedItemsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 6: google.protobuf.FieldMask
}
var file_internal_testpb_test_proto_depIdxs = []int32{
	5, // 0: tests.Shipment.create_time:type_name -> google.protobuf.Timestamp
	1, // 1: tests.Shipment.carrier:type_name -> tests.Carrier
	2, // 2: tests.Shipment.line_items:type_name -> tests.LineItem
	4, // 3: tests.Shipment.keyed_items:type_name -> tests.Shipment.KeyedItemsEntry
	0, // 4: tests.UpdateShipmentRequest.shipment:type_name -> tests.Shipment
	6, // 5: tests.UpdateShipmentRequest.update_mask:type_name -> google.protobuf.FieldMask
	2, // 6: tests.Shipment.KeyedItemsEntry.value:type_name -> tests.LineItem
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_testpb_test_proto_init() }
func file_internal_testpb_test_proto_init() {
	if File_internal_testpb_test_proto != nil {
		return
	}
	file_internal_testpb_test_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testpb_test_proto_rawDesc), len(file_internal_testpb_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testpb_test_proto_goTypes,
		DependencyIndexes: file_internal_testpb_test_proto_depIdxs,
		MessageInfos:      file_internal_testpb_test_proto_msgTypes,
	}.Build()
	File_internal_testpb_test_proto = out.File
	file_internal_testpb_test_proto_goTypes = nil
	file_internal_testpb_test_proto_depIdxs = nil
}
