// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/testpb/test.proto

// Package tests holds fixtures for exercising the pagination and ordering
// packages. It is not part of the public API.

package testpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre int32

const (
	Genre_GENRE_UNSPECIFIED Genre = 0
	Genre_GENRE_FICTION     Genre = 1
	Genre_GENRE_HISTORY     Genre = 2
)

// Enum value maps for Genre.
var (
	Genre_name = map[int32]string{
		0: "GENRE_UNSPECIFIED",
		1: "GENRE_FICTION",
		2: "GENRE_HISTORY",
	}
	Genre_value = map[string]int32{
		"GENRE_UNSPECIFIED": 0,
		"GENRE_FICTION":     1,
		"GENRE_HISTORY":     2,
	}
)

func (x Genre) Enum() *Genre {
	p := new(Genre)
	*p = x
	return p
}

func (x Genre) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genre) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_testpb_test_proto_enumTypes[0].Descriptor()
}

func (Genre) Type() protoreflect.EnumType {
	return &file_internal_testpb_test_proto_enumTypes[0]
}

func (x Genre) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genre.Descriptor instead.
func (Genre) EnumDescriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{0}
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_internal_testpb_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        *Author                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	ReadCount     int32                   `protobuf:"varint,4,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	PageCount     int64                   `protobuf:"varint,5,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	Checksum      uint64                  `protobuf:"varint,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Rating        float64                 `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	Published     bool                    `protobuf:"varint,8,opt,name=published,proto3" json:"published,omitempty"`
	Cover         []byte                  `protobuf:"bytes,9,opt,name=cover,proto3" json:"cover,omitempty"`
	Genre         Genre                   `protobuf:"varint,10,opt,name=genre,proto3,enum=tests.Genre" json:"genre,omitempty"`
	CreateTime    *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ReadDuration  *durationpb.Duration    `protobuf:"bytes,12,opt,name=read_duration,json=readDuration,proto3" json:"read_duration,omitempty"`
	Subtitle      *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Edition       *string                 `protobuf:"bytes,14,opt,name=edition,proto3,oneof" json:"edition,omitempty"`
	Tags          []string                `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	Labels        map[string]string       `protobuf:"bytes,16,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_internal_testpb_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Book) GetReadCount() int32 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *Book) GetPageCount() int64 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *Book) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *Book) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Book) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *Book) GetCover() []byte {
	if x != nil {
		return x.Cover
	}
	return nil
}

func (x *Book) GetGenre() Genre {
	if x != nil {
		return x.Genre
	}
	return Genre_GENRE_UNSPECIFIED
}

func (x *Book) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Book) GetReadDuration() *durationpb.Duration {
	if x != nil {
		return x.ReadDuration
	}
	return nil
}

func (x *Book) GetSubtitle() *wrapperspb.StringValue {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *Book) GetEdition() string {
	if x != nil && x.Edition != nil {
		return *x.Edition
	}
	return ""
}

func (x *Book) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Book) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_internal_testpb_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{2}
}

func (x *ListBooksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListBooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBooksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListBooksRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListBooksRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListBooksRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListBooksWithSkipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Skip          int32                  `protobuf:"varint,5,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksWithSkipRequest) Reset() {
	*x = ListBooksWithSkipRequest{}
	mi := &file_internal_testpb_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksWithSkipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksWithSkipRequest) ProtoMessage() {}

func (x *ListBooksWithSkipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksWithSkipRequest.ProtoReflect.Descriptor instead.
func (*ListBooksWithSkipRequest) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{3}
}

func (x *ListBooksWithSkipRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListBooksWithSkipRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBooksWithSkipRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListBooksWithSkipRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListBooksWithSkipRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// Shipment exercises field behavior (AIP-203) and field masks (AIP-134).
type Shipment struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Origin      string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Notes       string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	CarrierCode string                 `protobuf:"bytes,6,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	Carrier     *Carrier               `protobuf:"bytes,7,opt,name=carrier,proto3" json:"carrier,omitempty"`
	LineItems   []*LineItem            `protobuf:"bytes,8,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	KeyedItems  map[string]*LineItem   `protobuf:"bytes,9,rep,name=keyed_items,json=keyedItems,proto3" json:"keyed_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A presence-less required bool: `false` is indistinguishable from unset.
	Insured bool `protobuf:"varint,10,opt,name=insured,proto3" json:"insured,omitempty"`
	// An explicit-presence required bool: `false` is a real value.
	Fragile       *bool    `protobuf:"varint,11,opt,name=fragile,proto3,oneof" json:"fragile,omitempty"`
	Labels        []string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_internal_testpb_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{4}
}

func (x *Shipment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Shipment) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Shipment) GetCarrierCode() string {
	if x != nil {
		return x.CarrierCode
	}
	return ""
}

func (x *Shipment) GetCarrier() *Carrier {
	if x != nil {
		return x.Carrier
	}
	return nil
}

func (x *Shipment) GetLineItems() []*LineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *Shipment) GetKeyedItems() map[string]*LineItem {
	if x != nil {
		return x.KeyedItems
	}
	return nil
}

func (x *Shipment) GetInsured() bool {
	if x != nil {
		return x.Insured
	}
	return false
}

func (x *Shipment) GetFragile() bool {
	if x != nil && x.Fragile != nil {
		return *x.Fragile
	}
	return false
}

func (x *Shipment) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Carrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TrackingId    string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Carrier) Reset() {
	*x = Carrier{}
	mi := &file_internal_testpb_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Carrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carrier) ProtoMessage() {}

func (x *Carrier) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carrier.ProtoReflect.Descriptor instead.
func (*Carrier) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{5}
}

func (x *Carrier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Carrier) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_internal_testpb_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{6}
}

func (x *LineItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *LineItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentRequest) Reset() {
	*x = UpdateShipmentRequest{}
	mi := &file_internal_testpb_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentRequest) ProtoMessage() {}

func (x *UpdateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_testpb_test_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateShipmentRequest) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *UpdateShipmentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_internal_testpb_test_proto protoreflect.FileDescriptor

const file_internal_testpb_test_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/testpb/test.proto\x12\x05tests\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"6\n" +
	"\x06Author\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\"\x83\x05\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x06author\x18\x03 \x01(\v2\r.tests.AuthorR\x06author\x12\x1d\n" +
	"\n" +
	"read_count\x18\x04 \x01(\x05R\treadCount\x12\x1d\n" +
	"\n" +
	"page_count\x18\x05 \x01(\x03R\tpageCount\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\x04R\bchecksum\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\x12\x1c\n" +
	"\tpublished\x18\b \x01(\bR\tpublished\x12\x14\n" +
	"\x05cover\x18\t \x01(\fR\x05cover\x12\"\n" +
	"\x05genre\x18\n" +
	" \x01(\x0e2\f.tests.GenreR\x05genre\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12>\n" +
	"\rread_duration\x18\f \x01(\v2\x19.google.protobuf.DurationR\freadDuration\x128\n" +
	"\bsubtitle\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\bsubtitle\x12\x1d\n" +
	"\aedition\x18\x0e \x01(\tH\x00R\aedition\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\x12/\n" +
	"\x06labels\x18\x10 \x03(\v2\x17.tests.Book.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_edition\"\x91\x02\n" +
	"\x10ListBooksRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\x12;\n" +
	"\x06labels\x18\x06 \x03(\v2#.tests.ListBooksRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x18ListBooksWithSkipRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x12\n" +
	"\x04skip\x18\x05 \x01(\x05R\x04skip\"\xbf\x04\n" +
	"\bShipment\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1b\n" +
	"\x06origin\x18\x02 \x01(\tB\x03\xe0A\x02R\x06origin\x12%\n" +
	"\vdestination\x18\x03 \x01(\tB\x03\xe0A\x02R\vdestination\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12&\n" +
	"\fcarrier_code\x18\x06 \x01(\tB\x03\xe0A\x05R\vcarrierCode\x12(\n" +
	"\acarrier\x18\a \x01(\v2\x0e.tests.CarrierR\acarrier\x12.\n" +
	"\n" +
	"line_items\x18\b \x03(\v2\x0f.tests.LineItemR\tlineItems\x12@\n" +
	"\vkeyed_items\x18\t \x03(\v2\x1f.tests.Shipment.KeyedItemsEntryR\n" +
	"keyedItems\x12\x1d\n" +
	"\ainsured\x18\n" +
	" \x01(\bB\x03\xe0A\x02R\ainsured\x12\"\n" +
	"\afragile\x18\v \x01(\bB\x03\xe0A\x02H\x00R\afragile\x88\x01\x01\x12\x1b\n" +
	"\x06labels\x18\f \x03(\tB\x03\xe0A\x02R\x06labels\x1aN\n" +
	"\x0fKeyedItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.tests.LineItemR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_fragile\"H\n" +
	"\aCarrier\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12$\n" +
	"\vtracking_id\x18\x02 \x01(\tB\x03\xe0A\x03R\n" +
	"trackingId\"=\n" +
	"\bLineItem\x12\x15\n" +
	"\x03sku\x18\x01 \x01(\tB\x03\xe0A\x02R\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x86\x01\n" +
	"\x15UpdateShipmentRequest\x120\n" +
	"\bshipment\x18\x01 \x01(\v2\x0f.tests.ShipmentB\x03\xe0A\x02R\bshipment\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask*D\n" +
	"\x05Genre\x12\x15\n" +
	"\x11GENRE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rGENRE_FICTION\x10\x01\x12\x11\n" +
	"\rGENRE_HISTORY\x10\x02B2Z0github.com/protoc-contrib/aip-go/internal/testpbb\x06proto3"

var (
	file_internal_testpb_test_proto_rawDescOnce sync.Once
	file_internal_testpb_test_proto_rawDescData []byte
)

func file_internal_testpb_test_proto_rawDescGZIP() []byte {
	file_internal_testpb_test_proto_rawDescOnce.Do(func() {
		file_internal_testpb_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testpb_test_proto_rawDesc), len(file_internal_testpb_test_proto_rawDesc)))
	})
	return file_internal_testpb_test_proto_rawDescData
}

var file_internal_testpb_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_testpb_test_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_testpb_test_proto_goTypes = []any{
	(Genre)(0),                       // 0: tests.Genre
	(*Author)(nil),                   // 1: tests.Author
	(*Book)(nil),                     // 2: tests.Book
	(*ListBooksRequest)(nil),         // 3: tests.ListBooksRequest
	(*ListBooksWithSkipRequest)(nil), // 4: tests.ListBooksWithSkipRequest
	(*Shipment)(nil),                 // 5: tests.Shipment
	(*Carrier)(nil),                  // 6: tests.Carrier
	(*LineItem)(nil),                 // 7: tests.LineItem
	(*UpdateShipmentRequest)(nil),    // 8: tests.UpdateShipmentRequest
	nil,                              // 9: tests.Book.LabelsEntry
	nil,                              // 10: tests.ListBooksRequest.LabelsEntry
	nil,                              // 11: tests.Shipment.KeyedItemsEntry
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 13: google.protobuf.Duration
	(*wrapperspb.StringValue)(nil),   // 14: google.protobuf.StringValue
	(*fieldmaskpb.FieldMask)(nil),    // 15: google.protobuf.FieldMask
}
var file_internal_testpb_test_proto_depIdxs = []int32{
	1,  // 0: tests.Book.author:type_name -> tests.Author
	0,  // 1: tests.Book.genre:type_name -> tests.Genre
	12, // 2: tests.Book.create_time:type_name -> google.protobuf.Timestamp
	13, // 3: tests.Book.read_duration:type_name -> google.protobuf.Duration
	14, // 4: tests.Book.subtitle:type_name -> google.protobuf.StringValue
	9,  // 5: tests.Book.labels:type_name -> tests.Book.LabelsEntry
	10, // 6: tests.ListBooksRequest.labels:type_name -> tests.ListBooksRequest.LabelsEntry
	12, // 7: tests.Shipment.create_time:type_name -> google.protobuf.Timestamp
	6,  // 8: tests.Shipment.carrier:type_name -> tests.Carrier
	7,  // 9: tests.Shipment.line_items:type_name -> tests.LineItem
	11, // 10: tests.Shipment.keyed_items:type_name -> tests.Shipment.KeyedItemsEntry
	5,  // 11: tests.UpdateShipmentRequest.shipment:type_name -> tests.Shipment
	15, // 12: tests.UpdateShipmentRequest.update_mask:type_name -> google.protobuf.FieldMask
	7,  // 13: tests.Shipment.KeyedItemsEntry.value:type_name -> tests.LineItem
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_internal_testpb_test_proto_init() }
func file_internal_testpb_test_proto_init() {
	if File_internal_testpb_test_proto != nil {
		return
	}
	file_internal_testpb_test_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_testpb_test_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testpb_test_proto_rawDesc), len(file_internal_testpb_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testpb_test_proto_goTypes,
		DependencyIndexes: file_internal_testpb_test_proto_depIdxs,
		EnumInfos:         file_internal_testpb_test_proto_enumTypes,
		MessageInfos:      file_internal_testpb_test_proto_msgTypes,
	}.Build()
	File_internal_testpb_test_proto = out.File
	file_internal_testpb_test_proto_goTypes = nil
	file_internal_testpb_test_proto_depIdxs = nil
}
